In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.19.0


Create the tensor

In [3]:
a=tf.constant(5)
print(a)

tf.Tensor(5, shape=(), dtype=int32)


In [4]:
v=tf.constant([1,2,4])
print(v)

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [8]:
m=tf.constant([[3,4],[1,6]])
print(m)

tf.Tensor(
[[3 4]
 [1 6]], shape=(2, 2), dtype=int32)


In [9]:
n=tf.constant([[3,4],[1,6],[4,5]])
print(n)

tf.Tensor(
[[3 4]
 [1 6]
 [4 5]], shape=(3, 2), dtype=int32)


Tensors Addition

In [11]:
a=tf.constant([10,20,30])
b=tf.constant([30,40,60])
print(a+b)

tf.Tensor([40 60 90], shape=(3,), dtype=int32)


In [13]:
a=tf.constant([5,6,7])
b=tf.constant([9,3,1])
print(a*b)

tf.Tensor([45 18  7], shape=(3,), dtype=int32)


In [17]:
a=tf.constant([5,6,7])
b=tf.constant([9,3,1])
print(a-b)

tf.Tensor([-4  3  6], shape=(3,), dtype=int32)


In [ ]:
a=tf.constant([5,6,7])
b=tf.constant([9,3,1])
print(a-b)

Create two 2D tensors:

In [24]:
import tensorflow as tf

a = tf.constant([
    [1,2],
    [3,4]
])

b = tf.constant([
    [5,6],
    [7,8]
])


In [25]:
tf.add(a, b)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>

In [26]:
tf.subtract(a, b)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-4, -4],
       [-4, -4]], dtype=int32)>

In [27]:
tf.multiply(a, b)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [28]:
tf.divide(a, b)


<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])>

Create two 3D tensors:


In [18]:
a = tf.constant([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

b = tf.constant([
    [[1,1],[1,1]],
    [[2,2],[2,2]]
])


In [20]:
tf.add(a, b)



<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 2,  3],
        [ 4,  5]],

       [[ 7,  8],
        [ 9, 10]]], dtype=int32)>

In [21]:
tf.subtract(a, b)


<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[0, 1],
        [2, 3]],

       [[3, 4],
        [5, 6]]], dtype=int32)>

In [22]:
tf.multiply(a, b)


<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[10, 12],
        [14, 16]]], dtype=int32)>

In [23]:
tf.divide(a, b)

<tf.Tensor: shape=(2, 2, 2), dtype=float64, numpy=
array([[[1. , 2. ],
        [3. , 4. ]],

       [[2.5, 3. ],
        [3.5, 4. ]]])>

In [16]:
import numpy as np
np_array=np.array([[1,2,3],[4,5,6]])
tensor=tf.convert_to_tensor(np_array)
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)
